# -*- coding: utf-8 -*-
"""Copy of Assignment1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QIZS-Bh9QVOZHDdwQxZCO-1E13fuondu
"""

#Read the dataset to python environment.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

iris_data=pd.read_excel('/content/iris.xls')
iris_data

#Display the columns in the dataset.
iris_data.columns

#Calculate the mean of each column of the dataset.
iris_data.mean(axis=0)

#Check for the null values present in the dataset.
iris_data.isnull()

#Perform meaningful visualizations using the dataset. Bring at least 3 visualizations.
iris_data=pd.read_excel('/content/iris.xls')
iris_data

plt.hist(iris_data['Classification'])

plt.figure(figsize=(6,4))
plt.scatter(iris_data['SW'],iris_data['PL'],s=10)
plt.title('Plot of SW vs PL',fontsize=16)
plt.xlabel('SW')
plt.ylabel('PL')

sns.pairplot(iris_data)

plt.boxplot(iris_data['SL'])
plt.title('Box plot of SL')
plt.xlabel('SL')