# -*- coding: utf-8 -*-
"""Q&A assinment_Bineesh

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S8nP6u2M60UjJP6VQin7kp555oGiv8En
"""

import math
side = float(input('Enter the side of the equilateral triangle'))
area = math.sqrt(3) / 4 * side * side
print('Area of the equilateral triangle=',area)

str=input('Enter a string')
print('string is',str)
count={}
for i in str:
    if i in count.keys():
        count[i]+=1
    else: 
        count[i]=1
print(count)

l=float(input('length of the rectangle'))
b=float(input('breadth of the rectangle'))
area=l*b
perimeter=2*(l+b)
print('area of the rectangle is:',area)
print('perimeter of the rectangle:',perimeter)

number=int(input('Enter the number for multiplication table'))
for i in range(1,11):
    print(i,'*',number,'=',i*number)

x= int(input('Enter value of x:'))
y= int(input('Enter value of y:'))
if x==y:
  print("They are equal")
else:
 9
 Print("They are unequal")